### ISSUE TITLE
Simple Command in Time User Guide Does Not Execute

### ISSUE THREAD

**Issue by sdoken** [dato-code/userguide#75]
The [time series section of the User guide,](https://github.com/dato-code/userguide/blob/master/timeseries/timeseries-data.md) suggests we run

```python
ts_power = household_ts[['Global_reactive_power', 'Global_reactive_power']]
```

However, this does not execute properly on my local machine and graphlab complains about duplicate keys in key list as shown below:

![image](https://cloud.githubusercontent.com/assets/13375615/14668455/31c12e7a-0699-11e6-95dc-dde046eb1976.png)

**Comment by rbkreisberg** [comment]
@sdoken thanks for the report!
