### ISSUE TITLE
Quick start section is cut off

### ISSUE THREAD

**Issue by ellenyidong** [dato-code/userguide#79]
The quick start section is cut off. Users are not able to copy the full script here.
![image](https://cloud.githubusercontent.com/assets/15837905/15124345/93a27cd2-15dc-11e6-8d47-8dadda49d834.png)

**Comment by bianca-dato** [comment]
@rschindlauer @afranklin  I don't have access or a way to fix this issue since I don't handle User Guide would one of you investigate this issue or point me to where I can fix this?

**Comment by rschindlauer** [comment]
The table in https://github.com/dato-code/userguide/blob/master/install.md just needs a few linebreaks. You can do this in a new userguide repo branch and loop me into the PR.
