### ISSUE TITLE
Page loads with left sidebar in unexpected search mode

### ISSUE THREAD

**Issue by ellenyidong** [dato-code/userguide#91]
I reproduced one problem that @aatallah met before in one churn prediction meeting.

Google "recommender user guide" and click the first two search result
![image](https://cloud.githubusercontent.com/assets/15837905/16461590/19575b90-3de2-11e6-890a-be178c526147.png)

This is the confusing sidebar looks like. It becomes a search box with "evaluate" pre-filled. 
![image](https://cloud.githubusercontent.com/assets/15837905/16461626/4f30c45e-3de2-11e6-9e6c-9fcb4a9bdf0f.png)

The same problem occurs after clicking the search result of "churn prediction user guide" "classifier user guide" and almost every search result that links to a detailed chapter inside user guide.

**Comment by rschindlauer** [comment]
I can't reproduce it. Are you sure you didn't search for "evaluate" on the user guide page before? Search terms used previously in your browser will just stick around there, but I don't think they come from the Google link.

**Comment by ellenyidong** [comment]
@rschindlauer I see! I think that's because I've searched 'evaluate' before and user guide remembers my search, which is a little unexpected.

**Comment by rschindlauer** [comment]
I agree, it's not intuitive. Also, once you actually discover the search box and delete the string, the index is all expanded, which seems to be a gitbook bug. Having transitioned the PS docs to sphinx I believe that is the better doc framework anyways, so maybe we will move away from gitbook altogether at some point.
